spring:
  application:
    name: jardin

  datasource:
    url: ${url}
    username: ${User}
    password: ${Password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect